name: chattodo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  page_transition: ^2.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  uuid: ^4.4.2

dev_dependencies:

  #project management
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

  #data management
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

  fonts:
    - family: Paperlogy
      fonts:
        - asset: assets/fonts/Paperlogy/Paperlogy-1Thin.ttf
          weight: 100
        - asset: assets/fonts/Paperlogy/Paperlogy-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Paperlogy/Paperlogy-3Light.ttf
          weight: 300
        - asset: assets/fonts/Paperlogy/Paperlogy-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Paperlogy/Paperlogy-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Paperlogy/Paperlogy-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Paperlogy/Paperlogy-7Bold.ttf
          weight: 700
        - asset: assets/fonts/Paperlogy/Paperlogy-8ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Paperlogy/Paperlogy-9Black.ttf
          weight: 900

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.ttf
          weight: 900



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#303030"
  image: assets/icon/splash_icon.png
  android_12:
    color: "#ffffff"
    color_dark: "#303030"
    image: assets/icon/splash_icon.png
