name: todoredo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  uuid: ^4.4.2

dev_dependencies:

  #project management
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

  #data management
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true


  fonts:
    - family: JuaRegular
      fonts:
        - asset: assets/font/Jua-Regular.ttf
    - family: NotoSansKR
      fonts:
        - asset: assets/font/NotoSansKR/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/font/NotoSansKR/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/font/NotoSansKR/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansKR/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansKR/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansKR/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/font/NotoSansKR/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansKR/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/font/NotoSansKR/NotoSansKR-Black.ttf
          weight: 900

   
